name: Build & Publish Latest

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == 'YokiToki'
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set environment variables
      run: cat .env >> $GITHUB_ENV

    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64
        build-args: |
          OPENVPN_V=${{ env.OPENVPN_V }}
        tags: ghcr.io/yokitoki/openvpn:latest, ghcr.io/yokitoki/openvpn:${{ env.OPENVPN_V }}-${{ env.RELEASE }}
